# Generated by Django 3.2.8 on 2022-03-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=123)),
                ('email', models.EmailField(default='', max_length=254)),
                ('sem', models.IntegerField(default=1)),
            ],
        ),
    ]
